import { createAppRuntimeConfig } from "./app-runtime-config.js";
import { createAppServices } from "./app-services.js";
import { createGovernanceRuntime } from "./app-governance-runtime.js";
import { createAppGuardsAndAudit } from "./app-guards-and-audit.js";
import { createRouteDepsForApp } from "./app-route-wiring.js";
import { APP_ROUTE_REGISTRARS } from "./app-route-registrars.js";
import {
  isEnabled as isTelemetryEnabled,
  setEnabled as setTelemetryEnabled,
  getStats as getTelemetryStats,
  resetStats as resetTelemetryStats,
  createTelemetryMiddleware,
} from "../../telemetry.js";
import { HttpError } from "../shared/errors/HttpError.js";
import {
  CONFIG_KEYS,
  HEALTH_STATUS,
  INCIDENT_RUNBOOK_TYPES,
} from "../shared/app-constants.js";
import {
  areConfigValuesEqual,
  assertBodyObject,
  buildRagSystemMessage,
  buildSystemMessages,
  clamp,
  getChatId,
  getMessageImages,
  hasRequiredRole,
  normalizeRole,
  parseAuditFilters,
  parseAutoHealingConfigPatch,
  parseAutoHealingPolicy,
  parseBackupPassphrase,
  parseBackupPayload,
  parseBooleanLike,
  parseChatId,
  parseChatImportPayload,
  parseChatListFilters,
  parseCleanupMaxDeleteMb,
  parseCleanupMode,
  parseCleanupOlderThanDays,
  parseCleanupPreserveValidatedBackups,
  parseCleanupTarget,
  parseConfigVersionFilters,
  parseConfigVersionId,
  parseDisasterScenarioId,
  parseIncidentNextUpdateAt,
  parseIncidentOwner,
  parseIncidentRunbookMode,
  parseIncidentRunbookType,
  parseIncidentSummary,
  parseIncidentUpdatePayload,
  parseMessage,
  parseOperationalApprovalAction,
  parseOperationalApprovalDecision,
  parseOperationalApprovalId,
  parseOperationalApprovalReason,
  parseOperationalApprovalStatus,
  parseOperationalApprovalWindowMinutes,
  parseOptions,
  parseOriginList,
  parsePositiveInt,
  parseRagDocuments,
  parseRagOptions,
  parseSearchDate,
  parseSearchLimit,
  parseSearchPage,
  parseSearchQuery,
  parseSearchRole,
  parseStorageLimitMb,
  parseSystemPrompt,
  parseTags,
  parseTheme,
  parseTitle,
  parseUiPreferences,
  parseUserId,
  parseUserName,
  parseUserOnly,
  parseUserRole,
} from "../shared/parsers.js";
import { DEFAULT_RETRY_DELAYS_MS, executeWithModelRecovery } from "../shared/model-recovery.js";
import {
  buildOverallHealthStatus,
  buildSloSnapshot,
  buildTriageRecommendations,
} from "../modules/health/health-builders.js";
import {
  buildCorsOriginValidator,
} from "./app-bootstrap.js";

export function createAppContext({
  deps,
  store,
  serverDir,
  chatClient,
  logger,
  asyncHandler,
  registrars,
}) {
  const routeRegistrars = registrars || APP_ROUTE_REGISTRARS;

  const runtimeConfig = createAppRuntimeConfig({
    deps,
    serverDir,
    parseOriginList,
    HttpError,
    parsePositiveInt,
    DEFAULT_RETRY_DELAYS_MS,
    buildCorsOriginValidator,
  });

  const services = createAppServices({
    deps,
    store,
    serverDir,
    chatClient,
    ollama: {
      ollamaFallbackModel: runtimeConfig.ollamaFallbackModel,
      ollamaMaxAttempts: runtimeConfig.ollamaMaxAttempts,
      ollamaTimeoutMs: runtimeConfig.ollamaTimeoutMs,
      ollamaRetryDelays: runtimeConfig.ollamaRetryDelays,
    },
    parsers: {
      parsePositiveInt,
      parseSystemPrompt,
      parseTheme,
      parseStorageLimitMb,
      parseBooleanLike,
    },
    telemetry: {
      isTelemetryEnabled,
      setTelemetryEnabled,
      resetTelemetryStats,
      getTelemetryStats,
    },
    constants: {
      CONFIG_KEYS,
    },
  });

  const governanceRuntime = createGovernanceRuntime({
    deps,
    requestWindowMs:
      runtimeConfig.requestWindowMs ??
      Number.parseInt(process.env.RATE_LIMIT_WINDOW_MS || `${15 * 60 * 1000}`, 10),
    store,
    normalizeRole,
    getTelemetryStats,
    backupService: services.backupService,
    incidentService: services.incidentService,
    healthProviders: services.healthProviders,
    buildOverallHealthStatus,
    buildSloSnapshot,
    buildTriageRecommendations,
  });

  const guardsAndAudit = createAppGuardsAndAudit({
    store,
    logger,
    configRollbackService: services.configRollbackService,
    approvalService: services.approvalService,
    parseUserId,
    normalizeRole,
    hasRequiredRole,
    asyncHandler,
    HttpError,
    parseOperationalApprovalId,
  });

  const routeDeps = createRouteDepsForApp({
    core: {
      webDir: runtimeConfig.webDir,
      logger,
      HttpError,
      asyncHandler,
      HEALTH_STATUS,
      CONFIG_KEYS,
      INCIDENT_RUNBOOK_TYPES,
      store,
      chatClient,
    },
    registrars: routeRegistrars,
    guards: {
      requireMinimumRole: guardsAndAudit.requireMinimumRole,
      requireAdminOrSelf: guardsAndAudit.requireAdminOrSelf,
      resolveActor: guardsAndAudit.resolveActor,
      recordBlockedAttempt: guardsAndAudit.recordBlockedAttempt,
      requireOperationalApproval: guardsAndAudit.requireOperationalApproval,
    },
    runtime: {
      getTelemetryStats,
      isTelemetryEnabled,
      setTelemetryEnabled,
      resetTelemetryStats,
      roleLimiter: governanceRuntime.roleLimiter,
      ollamaFallbackModel: runtimeConfig.ollamaFallbackModel,
      ollamaMaxAttempts: runtimeConfig.ollamaMaxAttempts,
      ollamaTimeoutMs: runtimeConfig.ollamaTimeoutMs,
      ollamaRetryDelays: runtimeConfig.ollamaRetryDelays,
    },
    services: {
      healthProviders: services.healthProviders,
      integrityService: services.integrityService,
      autoHealingService: services.autoHealingService,
      capacityService: services.capacityService,
      queueService: services.queueService,
      baselineService: services.baselineService,
      backupService: services.backupService,
      collectIncidentRunbookSignals: governanceRuntime.collectIncidentRunbookSignals,
      incidentService: services.incidentService,
      disasterRecoveryService: services.disasterRecoveryService,
      storageService: services.storageService,
      readCurrentConfigValue: guardsAndAudit.readCurrentConfigValue,
      applyConfigValue: guardsAndAudit.applyConfigValue,
      approvalService: services.approvalService,
      scorecardService: services.scorecardService,
    },
    parsers: {
      parseBooleanLike,
      parseMessage,
      parseOptions,
      parseRagOptions,
      parseChatId,
      parseRagDocuments,
      parseSearchQuery,
      parseUserId,
      parseUserName,
      parseUserRole,
      parseSystemPrompt,
      parseTheme,
      parseUiPreferences,
      parseStorageLimitMb,
      parseTitle,
      parseChatListFilters,
      parseTags,
      parseSearchPage,
      parseSearchLimit,
      parseSearchRole,
      parseSearchDate,
      parseChatImportPayload,
      parseUserOnly,
      parseBackupPassphrase,
      parseBackupPayload,
      parsePositiveInt,
      parseIncidentUpdatePayload,
      parseIncidentRunbookType,
      parseIncidentRunbookMode,
      parseIncidentOwner,
      parseIncidentSummary,
      parseIncidentNextUpdateAt,
      parseAutoHealingConfigPatch,
      parseAutoHealingPolicy,
      parseDisasterScenarioId,
      parseCleanupMode,
      parseCleanupTarget,
      parseCleanupOlderThanDays,
      parseCleanupMaxDeleteMb,
      parseCleanupPreserveValidatedBackups,
      parseConfigVersionFilters,
      parseConfigVersionId,
      parseOperationalApprovalStatus,
      parseOperationalApprovalAction,
      parseOperationalApprovalReason,
      parseOperationalApprovalWindowMinutes,
      parseOperationalApprovalId,
      parseOperationalApprovalDecision,
      parseAuditFilters,
    },
    features: {
      assertBodyObject,
      recordAudit: guardsAndAudit.recordAudit,
      recordConfigVersion: guardsAndAudit.recordConfigVersion,
      buildOverallHealthStatus,
      buildSloSnapshot,
      getChatId,
      getMessageImages,
      buildRagSystemMessage,
      buildSystemMessages,
      executeWithModelRecovery,
      clamp,
      areConfigValuesEqual,
      buildTriageRecommendations,
    },
  });

  return {
    ...runtimeConfig,
    ...services,
    ...governanceRuntime,
    ...guardsAndAudit,
    createTelemetryMiddleware,
    routeDeps,
  };
}
