import { createAppRuntimeConfig } from "./app-runtime-config.js";
import { createAppServices } from "./app-services.js";
import { createGovernanceRuntime } from "./app-governance-runtime.js";
import { createAppGuardsAndAudit } from "./app-guards-and-audit.js";
import { createRouteDepsForApp } from "./app-route-wiring.js";

export function createAppContext({
  deps,
  store,
  serverDir,
  chatClient,
  logger,
  HttpError,
  asyncHandler,
  parseOriginList,
  parsePositiveInt,
  DEFAULT_RETRY_DELAYS_MS,
  buildCorsOriginValidator,
  telemetry,
  constants,
  normalizeRole,
  hasRequiredRole,
  parseUserId,
  parseOperationalApprovalId,
  requestWindowMsFallback,
  buildOverallHealthStatus,
  buildSloSnapshot,
  buildTriageRecommendations,
  registrars,
  parsers,
  features,
}) {
  const runtimeConfig = createAppRuntimeConfig({
    deps,
    serverDir,
    parseOriginList,
    HttpError,
    parsePositiveInt,
    DEFAULT_RETRY_DELAYS_MS,
    buildCorsOriginValidator,
  });

  const services = createAppServices({
    deps,
    store,
    serverDir,
    chatClient,
    ollama: {
      ollamaFallbackModel: runtimeConfig.ollamaFallbackModel,
      ollamaMaxAttempts: runtimeConfig.ollamaMaxAttempts,
      ollamaTimeoutMs: runtimeConfig.ollamaTimeoutMs,
      ollamaRetryDelays: runtimeConfig.ollamaRetryDelays,
    },
    parsers: {
      parsePositiveInt,
      parseSystemPrompt: parsers.parseSystemPrompt,
      parseTheme: parsers.parseTheme,
      parseStorageLimitMb: parsers.parseStorageLimitMb,
      parseBooleanLike: parsers.parseBooleanLike,
    },
    telemetry,
    constants,
  });

  const governanceRuntime = createGovernanceRuntime({
    deps,
    requestWindowMs: runtimeConfig.requestWindowMs ?? requestWindowMsFallback,
    store,
    normalizeRole,
    parsePositiveInt,
    getTelemetryStats: telemetry.getTelemetryStats,
    backupService: services.backupService,
    incidentService: services.incidentService,
    healthProviders: services.healthProviders,
    buildOverallHealthStatus,
    buildSloSnapshot,
    buildTriageRecommendations,
  });

  const guardsAndAudit = createAppGuardsAndAudit({
    store,
    logger,
    configRollbackService: services.configRollbackService,
    approvalService: services.approvalService,
    parseUserId,
    normalizeRole,
    hasRequiredRole,
    asyncHandler,
    HttpError,
    parseOperationalApprovalId: parsers.parseOperationalApprovalId,
  });

  const routeDeps = createRouteDepsForApp({
    core: {
      webDir: runtimeConfig.webDir,
      logger,
      HttpError,
      asyncHandler,
      HEALTH_STATUS: constants.HEALTH_STATUS,
      CONFIG_KEYS: constants.CONFIG_KEYS,
      INCIDENT_RUNBOOK_TYPES: constants.INCIDENT_RUNBOOK_TYPES,
      store,
      chatClient,
    },
    registrars,
    guards: {
      requireMinimumRole: guardsAndAudit.requireMinimumRole,
      requireAdminOrSelf: guardsAndAudit.requireAdminOrSelf,
      resolveActor: guardsAndAudit.resolveActor,
      recordBlockedAttempt: guardsAndAudit.recordBlockedAttempt,
      requireOperationalApproval: guardsAndAudit.requireOperationalApproval,
    },
    runtime: {
      getTelemetryStats: telemetry.getTelemetryStats,
      isTelemetryEnabled: telemetry.isTelemetryEnabled,
      setTelemetryEnabled: telemetry.setTelemetryEnabled,
      resetTelemetryStats: telemetry.resetTelemetryStats,
      roleLimiter: governanceRuntime.roleLimiter,
      ollamaFallbackModel: runtimeConfig.ollamaFallbackModel,
      ollamaMaxAttempts: runtimeConfig.ollamaMaxAttempts,
      ollamaTimeoutMs: runtimeConfig.ollamaTimeoutMs,
      ollamaRetryDelays: runtimeConfig.ollamaRetryDelays,
    },
    services: {
      healthProviders: services.healthProviders,
      integrityService: services.integrityService,
      autoHealingService: services.autoHealingService,
      capacityService: services.capacityService,
      queueService: services.queueService,
      baselineService: services.baselineService,
      backupService: services.backupService,
      collectIncidentRunbookSignals: governanceRuntime.collectIncidentRunbookSignals,
      incidentService: services.incidentService,
      disasterRecoveryService: services.disasterRecoveryService,
      storageService: services.storageService,
      readCurrentConfigValue: guardsAndAudit.readCurrentConfigValue,
      applyConfigValue: guardsAndAudit.applyConfigValue,
      approvalService: services.approvalService,
      scorecardService: services.scorecardService,
    },
    parsers: {
      parseBooleanLike: parsers.parseBooleanLike,
      parseMessage: parsers.parseMessage,
      parseOptions: parsers.parseOptions,
      parseRagOptions: parsers.parseRagOptions,
      parseChatId: parsers.parseChatId,
      parseRagDocuments: parsers.parseRagDocuments,
      parseSearchQuery: parsers.parseSearchQuery,
      parseUserId: parsers.parseUserId,
      parseUserName: parsers.parseUserName,
      parseUserRole: parsers.parseUserRole,
      parseSystemPrompt: parsers.parseSystemPrompt,
      parseTheme: parsers.parseTheme,
      parseUiPreferences: parsers.parseUiPreferences,
      parseStorageLimitMb: parsers.parseStorageLimitMb,
      parseTitle: parsers.parseTitle,
      parseChatListFilters: parsers.parseChatListFilters,
      parseTags: parsers.parseTags,
      parseSearchPage: parsers.parseSearchPage,
      parseSearchLimit: parsers.parseSearchLimit,
      parseSearchRole: parsers.parseSearchRole,
      parseSearchDate: parsers.parseSearchDate,
      parseChatImportPayload: parsers.parseChatImportPayload,
      parseUserOnly: parsers.parseUserOnly,
      parseBackupPassphrase: parsers.parseBackupPassphrase,
      parseBackupPayload: parsers.parseBackupPayload,
      parsePositiveInt,
      parseIncidentUpdatePayload: parsers.parseIncidentUpdatePayload,
      parseIncidentRunbookType: parsers.parseIncidentRunbookType,
      parseIncidentRunbookMode: parsers.parseIncidentRunbookMode,
      parseIncidentOwner: parsers.parseIncidentOwner,
      parseIncidentSummary: parsers.parseIncidentSummary,
      parseIncidentNextUpdateAt: parsers.parseIncidentNextUpdateAt,
      parseAutoHealingConfigPatch: parsers.parseAutoHealingConfigPatch,
      parseAutoHealingPolicy: parsers.parseAutoHealingPolicy,
      parseDisasterScenarioId: parsers.parseDisasterScenarioId,
      parseCleanupMode: parsers.parseCleanupMode,
      parseCleanupTarget: parsers.parseCleanupTarget,
      parseCleanupOlderThanDays: parsers.parseCleanupOlderThanDays,
      parseCleanupMaxDeleteMb: parsers.parseCleanupMaxDeleteMb,
      parseCleanupPreserveValidatedBackups:
        parsers.parseCleanupPreserveValidatedBackups,
      parseConfigVersionFilters: parsers.parseConfigVersionFilters,
      parseConfigVersionId: parsers.parseConfigVersionId,
      parseOperationalApprovalStatus: parsers.parseOperationalApprovalStatus,
      parseOperationalApprovalAction: parsers.parseOperationalApprovalAction,
      parseOperationalApprovalReason: parsers.parseOperationalApprovalReason,
      parseOperationalApprovalWindowMinutes:
        parsers.parseOperationalApprovalWindowMinutes,
      parseOperationalApprovalId: parsers.parseOperationalApprovalId,
      parseOperationalApprovalDecision: parsers.parseOperationalApprovalDecision,
      parseAuditFilters: parsers.parseAuditFilters,
    },
    features: {
      assertBodyObject: features.assertBodyObject,
      recordAudit: guardsAndAudit.recordAudit,
      recordConfigVersion: guardsAndAudit.recordConfigVersion,
      buildOverallHealthStatus,
      buildSloSnapshot,
      getChatId: features.getChatId,
      getMessageImages: features.getMessageImages,
      buildRagSystemMessage: features.buildRagSystemMessage,
      buildSystemMessages: features.buildSystemMessages,
      executeWithModelRecovery: features.executeWithModelRecovery,
      clamp: features.clamp,
      areConfigValuesEqual: features.areConfigValuesEqual,
      buildTriageRecommendations,
    },
  });

  return {
    ...runtimeConfig,
    ...services,
    ...governanceRuntime,
    ...guardsAndAudit,
    routeDeps,
  };
}
